# activation token
activation-token.expiration-hours=24

# scheduler
activation-token.cleanup.interval=6h

# URL documentation OpenAPI
quarkus.smallrye-openapi.path=/openapi

# Enable Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# JWT
mp.jwt.verify.issuer=https://house-rental.com
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem